server:
  port: 8081
  servlet:
    context-path: /auth

spring:
  profiles:
    active: localhost
  application:
    name: auth
  datasource:
    url: profile-specific
    username: profile-specific
    password: prfile-specific
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: create-drop

authentication:
  token-validation-time: 900000

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true

