spring:
  datasource:
    url: jdbc:mysql://localhost:3306/warehouse
    username: milosz
    password: slash123

auth:
  url: http://localhost:8081/auth
  admin-token: 'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhZG1pbiIsImV4cCI6MTc3OTUwODU3NH0.tUhro0xa41Nb8dgLImfpgNrxu4ZYHRnRaeKISKxOMAqaKYMBO35dloA1zaB_n6Vw8iFjvtJSo6mgL-PqYQeLXQ'