eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true

server:
  port: 8083
  servlet:
    context-path: /payment

spring:
  profiles:
    active: localhost
  datasource:
    url: profile-specific
    username: profile-specific
    password: prfile-specific
  application:
    name: payment
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: create-drop

auth:
  url: http://localhost:8081/auth
  admin-token: 'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhZG1pbiIsImV4cCI6MTc3OTUwODU3NH0.tUhro0xa41Nb8dgLImfpgNrxu4ZYHRnRaeKISKxOMAqaKYMBO35dloA1zaB_n6Vw8iFjvtJSo6mgL-PqYQeLXQ'